// LOCATIONS
export const UPDATE_FLIGHT_LOCATIONS = 'UPDATE_FLIGHT_LOCATIONS'
export const UPDATE_FLIGHT_ORIGIN = 'UPDATE_FLIGHT_ORIGIN'
export const UPDATE_FLIGHT_DESTINATION = 'UPDATE_FLIGHT_DESTINATION'

// MEMBERS
export const UPDATE_FLIGHT_MEMBERS = 'UPDATE_FLIGHT_MEMBERS'

// DATES
export const UPDATE_FLIGHT_DATES = 'UPDATE_FLIGHT_DATES'
export const UPDATE_FLIGHT_TYPE = 'UPDATE_FLIGHT_TYPE'